name: Deploy AWS Lambda

on:
  workflow_dispatch:  # allows manual trigger
  push:
    branches:
      - main

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies (if any)
      - name: Install dependencies
        run: |
          cd lambda-cicd/lambda
          if [ -f requirements.txt ] && [ -s requirements.txt ]; then
            echo "Installing dependencies..."
            pip install -r requirements.txt -t .
          else
            echo "No dependencies to install"
          fi

      # Step 3: Package Lambda function
      - name: Package Lambda function
        run: |
          cd lambda-cicd/lambda
          zip -r lambda.zip .
          mv lambda.zip ../../

      # Step 4: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 5: Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        run: |
          if [ -f lambda.zip ]; then
            echo "Deploying Lambda function..."
            aws lambda update-function-code \
              --function-name my-test-cicd-lambda \
              --zip-file fileb://lambda.zip
          else
            echo "No zip file found. Deployment skipped."
          fi
