name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
  

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Step 3: Install dependencies if requirements.txt exists
      - name: Install dependencies
        run: |
          cd lambda-cicd/lambda
          if [ -f requirements.txt ] && [ -s requirements.txt ]; then
            pip install -r requirements.txt -t .
          else
            echo "No dependencies to install"
          fi

      # Step 4: Package lambda function
      - name: Package Lambda function
        run: |
          cd lambda-cicd/lambda
          zip -r lambda.zip .
          mv lambda.zip ../../
          cd ../..

      # Step 5: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 6: Deploy to AWS Lambda (only if zip exists)
      - name: Deploy to AWS Lambda
        run: |
          if [ -f lambda.zip ]; then
            echo "Deploying Lambda function..."
            aws lambda update-function-code \
              --function-name my-test-cicd-lambda\
              --zip-file fileb://lambda.zip
          else
            echo "No zip file found. Deployment skipped."
          fi
