name: Deploy AWS Lambda with AWS Profile

on:
  push:
    branches:
      - main
  

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Step 3: Install dependencies if requirements.txt exists
      - name: Install dependencies
        run: |
          cd lambda-cicd/lambda
          if [ -f requirements.txt ] && [ -s requirements.txt ]; then
            echo "Installing dependencies..."
            pip install -r requirements.txt -t .
          else
            echo "No dependencies to install"
          fi

      # Step 4: Package Lambda function
      - name: Package Lambda function
        run: |
          cd lambda-cicd/lambda
          zip -r lambda.zip .
          mv lambda.zip ../../
          cd ../..

      # Step 5: Configure AWS CLI profile
      - name: Configure AWS CLI profile 'dev'
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile dev
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile dev
          aws configure set region us-east-1 --profile dev

      # Step 6: Debug - list files
      - name: List files
        run: |
          echo "Files in lambda folder:"
          ls -R lambda-cicd/lambda
          echo "Check lambda.zip at root:"
          ls -l lambda.zip

      # Step 7: Deploy to AWS Lambda using 'dev' profile
      - name: Deploy to AWS Lambda
        run: |
          if [ -f lambda.zip ]; then
            echo "Deploying Lambda function using profile 'dev'..."
            aws lambda update-function-code \
              --function-name my-test-cicd-lambda \
              --zip-file fileb://lambda.zip \
              --profile dev
          else
            echo "No zip file found. Deployment skipped."
