name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'lambda-cicd/lambda/**'
  

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          cd lambda-cicd/lambda
          pip install -r requirements.txt -t .

      - name: Package lambda function
        run: |
          cd lambda-cicd/lambda
          zip -r ../../lambda.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name my-test-cicd-lambda \
            --zip-file fileb://lambda.zip
