name: Deploy AWS Lambda                   # workflow name
on:                                       
  push:                                   # Run this workflow when is pushed
    branches:
      - main                              # only if push is on the "main" branch
    paths:
      'lambda/**'                         # only if files inside the "lambda" folder are changed

jobs:
  deploy-lambda:
    runs-on: ubuntu latest                # Use GitHub's ubuntu latest runner
    steps:
      - name: checkout repository
        uses: action/checkout@v4          # Get your repo code so the runner can access file like lambda/

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'         # Installs python 3.13 (needed if lambda uses python + dependencies)

      - name: Install dependencies
        run:  |
          cd lambda
          pip install -r requirement.txt -t .
        # Gose into lambda folder
        # Installs python packages from requirements.txt into the same folder
        # Ensure dependencies are packaged with lambda code

      - name: Package lamdda function
        run:  |
          cd lambda
          zip -r lambda.zip .
          # Zips everything in the lambda folder (.)

        # Zips everything in the lambda folder (.)
        # Saves the zip one level up (../) so it’s not zipped into itself
        # Output file: lambda.zip (ready to upload to AWS)

      - name: Configure AWS Credentials
        uses: aws-action/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        # Authenticates to AWS using GitHub Secrets
        # Lets later AWS CLI commands know "who you are" and "where to deploy"

      - name: Deploy to AWS Lamda
        run:  |
          aws lambda update-function-code \
            --function-name my-test-cicd-lambda \
            --zip-file fileb://lambda.zip
        # Uses AWS CLI to upload the zip file to your Lambda function





        


